### ISSUE TITLE
Maintainership request

### ISSUE THREAD

**Issue by ocharles** [archambaultv/sexpresso#11]
Hi @archambaultv, I just saw

> If you wish to take over the project please contact me.

As we actively use `sexpresso` at work I'm interested in keeping it buildable. We don't anticipate needing any changes, so I'd like to request to be a co-maintainer so I can do basic tasks like adjusting version bounds and uploading to Hackage. If you're interested in this, could you add me as a collaborator to this GitHub repository, and grant `OliverCharles` maintainer rights on Hackage?

**Comment by archambaultv** [comment]
Thank you for you help ! 
I granted you the maintainer rights on Hackage and sent you and invitation on Github to become a collaborator.
