### ISSUE TITLE
r5rs & negative numbers

### ISSUE THREAD

**Issue by rd--** [archambaultv/sexpresso#7]
hello - in the test below "-1" won't parse? - it says "The previous two atoms are not separated by space" - i think r5rs scheme allows this? - ie. writing negative numbers without applying unary negate as (- 1) - best, rd

~~~~
import Data.Void {- base -}

import qualified Text.Megaparsec as M {- megaparsec -}

import qualified Data.SExpresso.Parse as S {- sexpresso -}
import qualified Data.SExpresso.SExpr as S {- sexpresso -}
import qualified Data.SExpresso.Language.SchemeR5RS as S {- sexpresso -}

-- > parse_sexp "-1"
parse_sexp :: String -> Either (M.ParseErrorBundle String Void) [S.SExpr S.SExprType S.SchemeToken]
parse_sexp = M.parse (S.decode S.sexpr) ""
~~~~

**Comment by archambaultv** [comment]
Hello. Very sorry for this long delay. You are right I can reproduce this issue. I will fix it hopefully today or tomorrow.

**Comment by archambaultv** [comment]
Version 1.1.0.0 availabe on Hackage and on the master branch solves this issue. Thank you.

**Comment by rd--** [comment]
hello - excellent news! - many thanks - best, rd
